name: lint-js

on:
  workflow_call:
    inputs:
      lint-command:
        description: "Lint command to run after npm ci"
        type: string
        default: "npx eslint ."
        required: false

jobs:
  eslint:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: ${{ inputs.lint-command }}
