name: lint-js

on:
  workflow_call:
    inputs:
      lint-command:
        description: "Lint command to run after npm ci"
        type: string
        default: "npx eslint ."
        required: false

jobs:
  eslint:
    runs-on: [self-hosted, macOS]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: npm ci
      - run: ${{ inputs.lint-command }}
